## Домашняя работа №1
Знакомство с библиотекой numpy

1. Импорт библиотеки NumPy с общепринятым сокращением.

In [1]:
# импортирование библиотеки
import numpy as np

2. Примеры создания массивов

In [2]:
# массив из списка
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
# массив из нулей 2x5
zeros = np.zeros((2,5))

# массив из единиц 3x4
ones = np.ones((3,4))

# массив через arange со значениями от 1 до 20 с шагом 5
arange = np.arange(1,20,5)

print(a)
print(zeros)
print(ones)
print(arange)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[ 1  6 11 16]


3. Демонстрация атрибутов

In [3]:
# выод формы массива
print(a.shape)

# вывод типа данных массива 
print(a.dtype)

(3, 3)
int64


4. Примеры индексирования и срезов

In [4]:
# получение отдельного элемента (второго элемента первой строки)
print(a[0][1])

#извлечение подмассивов
print(a[:2])
c = np.arange(10)
print("c =",c)
d = c[4:8]
print("d =",d)



2
[[1 2 3]
 [4 5 6]]
c = [0 1 2 3 4 5 6 7 8 9]
d = [4 5 6 7]


5. Примеры векторных операций и базовых статистик

In [5]:
print(a)
ones = np.ones((3,3))

# поэлементное сложение массивов
print(a+ones)

b=a.copy()

# поэлементное умножение массивов
print(a*b)

# вычисление среднего значения массива
print("Среднее равно:", a.mean())

# вычисление суммы элементов массива
print("Сумма равна:",a.sum())


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
Среднее равно: 5.0
Сумма равна: 45
